### ISSUE TITLE
I want to inject decorator one time only in the stage

### ISSUE THREAD

**Issue by MasilamaniSeenivasan** [n3wt0n/AzurePipelinesDecoratorSamples#3]
For example, I have a stage with 3 jobs, but I expected to inject decorator for the first job only.
how to use conditional injection in this case?

**Comment by n3wt0n** [comment]
You could use `System.JobDisplayName`, `System.JobId`, or `System.JobName` to discriminate on the job.

Something like:

```yaml
steps:
- ${{ if eq(variables['System.JobName'], 'MyJobName') }}:
  - task: CmdLine@2
  [...]
```
