### ISSUE TITLE
Help needed!! How to avoid injection in "-deployment"?

### ISSUE THREAD

**Issue by MasilamaniSeenivasan** [n3wt0n/AzurePipelinesDecoratorSamples#5]
![image](https://user-images.githubusercontent.com/59478616/144617546-3113db81-15ab-4422-bcca-1dbc1674377e.png)

when I am using the above yaml, Decorator injected twice, one for **-deployment** and another for **-job**.
I wants to exclude the injection for **-deploymen**t, What is the condition I have to use to achieve this?

**Comment by n3wt0n** [comment]
Unfortunately there is no "direct way" to achieve that.

The way I've been doing it is checking on the `Environment.Id` variable. This works because a deployment job should have a connected environment.

In you decorator YAML you can use something like this:

```yaml
steps:
- ${{ if (eq(variables['Environment.Id'], '') ) }}:
  - task:
    [WHATEVER ELSE YOU HAVE]
```

Which basically injects the decorator only when the Environment is not set
